# Generated by Django 3.1 on 2020-08-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('no', models.AutoField(db_column='No', primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=45, null=True)),
                ('writer', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('answer', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
    ]
